MIN_GAME_SIZE = 7;
MAX_GAME_SIZE = 30;
MAX_ROLE_COUNT = 3;

adminNames = ["cpi"];

debugNames = ["John",
			  "Rose",
			  "Dave",
			  "Jade",
			  "Jane",
			  "Jake",
			  "Roxy",
			  "Dirk",
			  "Karkat",
			  "Aradia",
			  "Tavros",
			  "Sollux",
			  "Terezi",
			  "Kanaya",
			  "Nepeta",
			  "Vriska",
			  "Equius",
			  "Gamzee",
			  "Eridan",
			  "Feferi",
			  "Davesprite",
			  "Dad",
			  "Jack",
			  "WV",
			  "PM",
			  "AR",
			  "WQ",
			  "WK",
			  "cpi",
			 ];

phaseStyleDict = {"Game Start":		"gs",
				  "Day":			"dy",
				  "Night":			"nt",
				  "Village Win":	"vw",
				  "Witch Win":		"ww",
				  };

masterExpansionList = ["Halftime",
					   "King's Court",
					   "Love & War"]

masterTeamDict = {   0: "Village Peasant",
				     1: "Holy Villager",
				     2: "Village Spy",
				     3: "Village Knight",
				     4: "Village Lover",
				  '-1': "Witch",
				  '-2': "Junior Witch",
				  '-3': "Traitor",
				  '-4': "Warlock",
				  };
				  
abbrevTeamDict = {   0: "V",
				     1: "H",
				     2: "S",
				     3: "K",
				     4: "L",
				  '-1': "W",
				  '-2': "J",
				  '-3': "T",
				  '-4': "R",
				  };

masterRoleList =   ["Priest",
					"Judge",
					"Dirty Old Bastard",
					"Hunter",
					"Survivalist",			//index 4
					"Gambler",
					"Fanatic",
					"Gravedigger",
					"Apprentice",
					"Oracle",				//index 9
					"Peeping Tom",
					"Peeping Tim",
					"Acolyte",
					"Loose Cannon",
					"Bomber",				//index 14
					"Assassin",
					"Emissary",
					"Benevolent Old Dame",
					"Nurse",
					"Spiritualist",			//index 19
					"Inquisitor",
					"Detective",
					"Bishop",
					"Daredevil",
					"Magician",				//index 24
					"Conspirator",
					"Con Artist",
					"Knife Thrower",
					"Investigator",
					"Innkeeper",			//index 29
					"Butcher",
					"Alchemist",
					"Entertainer",
					"Clown",
					"King",					//index 34
					"Queen",
					"Undertaker",
					"Squire",
					"Jester",
					"Count",				//index 39
					"Vizier",
					"Vigilante",
					"Traveling Medic",
					"Traveling Mercenary",
					"Traveling Mystic",		//index 44
					"Traveling Minstrel",
					"Templar",
					"Lookout",
					"Captain",
					"Matchmaker",			//index 49
					"Ninja",
					"Seducer",
					"Rogue",
					"Blacksmith",
					"Engineer",				//index 54
					"Executioner",
					"Copycat",
					"Admiral",
					"Vampire Hunter"];		//index 58

abbrevRoleList =   ["P",
					"J",
					"DOB",
					"H",
					"S",
					"G",
					"F",
					"GD",
					"A",
					"O",
					"PTOM",
					"PTIM",
					"ACO",
					"LC",
					"BMB",
					"ASN",
					"EM",
					"BOD",
					"N",
					"SP",
					"INQ",
					"DET",
					"B",
					"DD",
					"M",
					"CNS",
					"CA",
					"KT",
					"INV",
					"INN",
					"BTC",
					"ALC",
					"E",
					"C",
					"K",
					"Q",
					"U",
					"SQ",
					"JST",
					"CNT",
					"VZ",
					"VIG",
					"TMD",
					"TMR",
					"TMY",
					"TML",
					"T",
					"L",
					"CPT",
					"MM",
					"NJ",
					"SD",
					"R",
					"BS",
					"ENG",
					"EX",
					"CC",
					"ADM",
					"VH"];

masterTeamBreakpointDict = 	{"-1": [3,6,9,14,19], //do not include holies or peasants!
							};

masterHolyRoleList = 		[0,12,22,34,46];
masterMandatoryRoleList = 	[0,1,4,7];
masterDisabledRoleList =	[12,13,14,15,16,17,18,19,20,21,22,23,24];
masterRoleDependencyDict =  { 8: [1,7], //nesting not allowed
							  9: [0],
							 12: [0],
							 29: [20,28],
							 35: [34],
							 37: [34],
							 38: [34],
							 39: [34],
							 40: [34],
							 41: [34],
							 45: [42,43,44],
							 48: [47],
							 57: [47],
							};

masterExpansionDependencyDict =  {25: [0],
							  	  34: [1],
							 	  37: [1],
							 	  49: [2],
								 };

masterExpansionRequirementDict = {1: [34]}; //king required in KC games; check at startGame

masterTeamBreakpointDict = {"-1": [3,6,9,14,19], //do not include holies or peasants!
							};

deathLocationStringDict = { 0: "Across from the Alehouse",
						    1: "Beneath a Bridge",
							2: "Close to the Church",
							3: "Down by the Docks",
							4: "Round the Riverbend",
							5: "in Front of the Fields",
							6: "Towards the Turnpike",
							7: "Halfway down a Hill",
							8: "Inside the Inn",
							9: "Stuffed inside a Scarecrow",
						   10: "Within a Well",
						   11: "Left in a Lake",
						   12: "in the Middle of Nowhere",
						   13: "Vanquished in the Valley",
						   14: "Perched on a Pig Pen",
						   15: "Under the Underbrush",
						   77: "lying in the town square",
						   };




logPermissionsDict = {
	'$ACO': {'actors': ['c12'], 'targets': ['c0'], 'updateActors': ['c0'], },
	'$ADM': {'alive': ['c57'], 'actors': ['c57'], 'targets': ['pA', 'x'], 'statusCodes': ['m'], 'mayKillBool': ['pA', 'x'], 'updateDead': ['c57'], },
	'$ALC': {'alive': ['c31'], 'actors': ['c31'], 'targets': ['pA', 'x'], 'statusCodes': ['m'], 'extraLifeBool': ['pA', 'x'], 'updateDead': ['c31'], },
	'$A': {'actors': ['c8'], 'targets': ['cpT'], 'selectedRoleIndex': ['pA'], 'updateActors': ['cpT'], },
	'$ASN': {'correntRoleIndex': ['cpT'], 'updateAll': ['c15'], },
	'$B': {'alive': ['c22'], 'actors': ['c22'], 'targets': ['pA', 'x', 'gc'], 'updateActors': ['tpT', 't-1'], 'updateDead': ['c22'], },
	'$BS': {'selfExtraLifeCount': ['m'], 'updateAll': ['c53'], },
	'$BOD': {'targetExtraLifeCount': ['m'], 'updateAll': ['c17'], },
	'$BODS': {'tag': ['c17'], },
	'$BMR1': {'actors': ['c14'], },
	'$BMR2': {'alive': ['c14'], 'actors': ['c14'], 'targets': ['pA', 'x'], 'statusCodes': ['m'], 'updateDead': ['c14'], },
	'$BTC': {'alive': ['c30'], 'actors': ['c30'], 'targets': ['pA', 'x'], 'statusCodes': ['m'], 'updateDead': ['c30'], },
	'$CPT1': {'updateAll': ['[captainID]'], },
	'$CPT2': {'selfExtraLifeCount': ['m'], },
	'$CPT3': {},
	'$C': {'alive': ['c33'], 'actors': ['c33'], 'targets': ['pA', 'x'], 'statusCodes': ['m'], 'updateDead': ['c33'], },
	'$CA': {'alive': ['c26'], 'actors': ['c26'], 'targets': ['pA', 'x'], 'statusCodes': ['m'], 'resultCardList': ['pA', 'x'], 'updateActors': ['allT'], 'updateDead': ['c26'], },
	'$CON1': {'actors': ['c25'], 'targets': ['pT'], 'spyRoleIndexListList': ['pA', 'pT'], },
	'$CON2': {'alive': ['c25'], 'actors': ['c25'], 'selfExtraLifeCount': ['m'], },
	'$CNT': {'alive': ['c39'], 'actors': ['c39'], 'teamIndex': ['pA', 'x'], 'result': ['pA', 'x'], 'updateDead': ['c39'], },
	'$DD1': {'alive': ['c23'], 'actors': ['c23'], },
	'$DD2': {'alive': ['c23'], 'actors': ['c23'], 'targets': ['pA', 'x'], 'updateDead': ['c23'], },
	'$DOB': {'updateAll': ['c2'], },
	'$DOBS': {'tag': ['c2'], },
	'$D': {'resultCardList': ['allT'], 'updateAll': ['c21'], },
	'$EM1': {'actors': ['c16'], },
	'$EM2': {'alive': ['c16'], 'actors': ['c16'], },
	'$ENG1': {'updateAll': ['c54'], },
	'$ENG2': {},
	'$ENG3': {'statusCodes': ['m'], },
	'$E': {'alive': ['c32'], 'actors': ['c32'], 'targets': ['pA', 'x'], 'statusCodes': ['m'], 'witchNum': ['m'], 'trueTargetID': ['m'], 'updateDead': ['c32'], },
	'$EX': {'updateAll': ['c55'], },
	'$F1': {'tag': ['pA', 'x'], 'selfExtraLifeCount': ['m'], 'updateDead': ['c6'], },
	'$F2': {'tag': ['c0', 'pA', 'x'], 'actors': ['c6'], 'selfExtraLifeCount': ['m'], 'updateActors': ['c0'], 'updateDead': ['c6'], },
	'$G1': {'actors': ['c5'], 'selectionInt': ['pA'], },
	'$G2': {'tag': ['pA'], },
	'$GD': {'alive': ['cpA'], 'actors': ['cpA'], 'resultCardList': ['allT'], 'deadGravediggerID': ['c7'], 'updateActors': ['allT'], 'updateDead': ['cpA', 'allT'], },
	'$H1': {'alive': ['c3'], 'actors': ['c3'], },
	'$H2': {'alive': ['c3'], 'actors': ['c3'], },
	'$H3': {'alive': ['c3'], 'actors': ['c3'], 'targets': ['pA', 'x'], 'statusCodes': ['m'], 'updateDead': ['c3'], },
	'$INN': {'actors': ['c20', 'c29'], 'updateActors': ['c20', 'c29'], 'updateTargets': ['[investigatorID,', 'innkeeperID]'], },
	'$INQ': {'actors': ['c20', 'c29'], 'targets': ['pA', 'x'], 'resultCategoryIndex': ['pA', 'x'], 'aliveInnkeeperID': ['c29'], 'updateDead': ['c20', 'c29'], },
	'$INV': {'actors': ['c28', 'c29'], 'targets': ['pA', 'x'], 'resultCategoryIndex': ['pA', 'x'], 'aliveInnkeeperID': ['c29'], 'updateDead': ['c28', 'c29'], },
	'$JST1': {'alive': ['c38'], 'actors': ['c38'], },
	'$JST2': {'alive': ['c38'], 'actors': ['c38'], 'statusCodes': ['m'], 'updateDead': ['c38'], },
	'$J': {'alive': ['cpA'], 'actors': ['cpA'], 'extraLivesBurned': ['m'], 'deadJudgeID': ['c1'], 'updateActors': ['allT'], 'updateDead': ['cpA'], },
	'$K1': {'actors': ['c34'], },
	'$K2': {'alive': ['c34', 'gk'], 'actors': ['gk'], 'targets': ['gk'], 'kingID': ['c34'], 'updateActors': ['c34', 'c40'], 'updateDead': ['c34', 'c40'], },
	'$KT': {'alive': ['c27'], 'actors': ['c27'], 'targets': ['pA', 'x'], 'statusCodes': ['m'], 'updateDead': ['c27'], },
	'$L1': {'actors': ['c47'], 'alarmTypeIndex': ['pA'], },
	'$L2': {'alive': ['c47'], 'actors': ['c47'], 'alarmTypeIndex': ['pA'], 'deadRatioList': ['m'], 'selfExtraLifeCount': ['m'], },
	'$LC': {'statusCodes': ['m'], 'updateAll': ['c13'], },
	'$M1': {'alive': ['c24'], 'actors': ['c24'], },
	'$M2': {'alive': ['c24'], 'actors': ['c24'], 'statusCodes': ['m'], 'updateDead': ['c24'], },
	'$MM1': {'actors': ['c49'], 'targets': ['pT'], 'loverRoleIndexListList': ['pA', 'pT'], },
	'$MM2': {'alive': ['c49'], 'actors': ['c49'], },
	'$N': {'targets': ['cpT'], 'targetExtraLifeCount': ['m'], 'updateAll': ['c18'], },
	'$NJ1': {'updateAll': ['c50'], },
	'$NJ2': {},
	'$NJ3': {},
	'$O': {'actors': ['c9'], 'priestDeathLocationIndex': ['pA'], },
	'$P': {'alive': ['c0'], 'actors': ['c0'], 'targets': ['pA', 'x'], 'resultIsCovenBool': ['pA', 'x'], 'shenanigansBool': ['x'], 'updateDead': ['c0'], },
	'$PT1': {'actors': ['c11'], 'targets': ['pA'], },
	'$PT2': {'actors': ['c10'], 'targets': ['pA'], },
	'$Q': {'alive': ['c35', 'gk1'], 'actors': ['gk'], 'targets': ['gk'], 'updateActors': ['c35'], 'updateDead': ['c35'], },
	'$R': {'updateAll': ['c52'], },
	'$SD1': {'updateAll': ['c51'], },
	'$SD2': {},
	'$SD3': {'lookBool': ['pA', 'pT', 'x'], 'killBool': ['pA'], },
	'$SD4': {'tag': ['pA', 'pT', 'x'], 'updateTargets': ['allA'], 'updateDead': ['allA'], },
	'$SD5': {'tag': ['pA', 'pT', 'x'], },
	'$SQ1': {'actors': ['c37'], 'targets': ['pT'], 'knightRoleIndexListList': ['pA', 'pT'], },
	'$SQ2': {'tag': ['c37'], 'selfExtraLifeCount': ['m'], },
	'$S': {'actors': ['c4'], },
	'$T1': {'updateAll': ['c46'], },
	'$T2': {},
	'$TMD': {'alive': ['c42'], 'actors': ['pA', 'x'], 'targets': ['pA', 'x'], 'medicID': ['c42'], 'secondUseBool': ['pA', 'x'], 'targetSameTeamBool': ['m'], 'targetExtraLifeCount': ['m'], 'updateActors': ['c42'], 'updateDead': ['c42'], },
	'$TMR': {'alive': ['c43'], 'actors': ['pA', 'x'], 'targets': ['pA', 'x'], 'statusCodes': ['m'], 'mercenaryID': ['c43'], 'secondUseBool': ['pA', 'x'], 'updateActors': ['c43'], 'updateDead': ['c43'], },
	'$TMY': {'alive': ['c44'], 'actors': ['pA', 'x'], 'targets': ['pA', 'x'], 'mysticID': ['c44'], 'secondUseBool': ['pA', 'x'], 'updateActors': ['c44'], 'updateDead': ['c44'], },
	'$TML': {'alive': ['c45'], 'actors': ['pA', 'x'], 'targets': ['pA', 'x'], 'minstrelID': ['c45'], 'updateActors': ['c45'], 'updateDead': ['c45'], },
	'$U1': {'actors': ['c36'], 'updateDead': ['c36'], },
	'$U2': {'actors': ['c36'], 'resultCardList': ['allT'], 'updateActors': ['allT'], 'updateDead': ['allT'], },
	'$VH1': {'actors': ['c58'], },
	'$VH2': {'tag': ['c58'], 'actors': ['c58'], },
	'$VIG1': {'tag': ['pA'], },
	'$VIG2': {'alive': ['c41'], 'actors': ['c41'], 'targets': ['pA', 'x'], 'statusCodes': ['m'], },
	'$VZ': {'alive': ['c40'], 'targets': ['td'], 'vizierID': ['c40'], 'disbandBool': ['td'], 'updateActors': ['c40'], 'updateDeadDelayed': ['c40'], },
	'@START': {},
	'@A': {'teamIndex': ['tpA'], 'roleIndex1': ['cV'], 'roleIndex2': ['cV'], 'roleIndex3': ['cV'], 'roleIndex4': ['cV'], 'updateActors': ['allA'], },
	'@CL': {},
	'@TC': {},
	'@RT': {'tag': ['pA', 'pT'], },
	'@STALE': {},
	'@WIN': {},
	'@REPLACE': {},
	'@WARN': {},
	'@MK': {},
	'@MKR': {},
	'@X': {'updateDead': ['allA'], },
	'@V': {},
	'@KV': {'tag': ['gk'], },
	'@CV': {'tag': ['gc'], },
	'@CIV': {'tag': ['gc'], },
	'@CRV': {'tag': ['gc'], },
	'@AV': {'tag': ['xa'], },
	'@DV': {'tag': ['xd'], },
	'@LK': {'statusCodes': ['m'], },
	'@KK': {'tag': ['gk', 'x'], 'statusCodes': ['m'], },
	'@CK': {'tag': ['gc', 'x'], 'statusCodes': ['m'], },
	'@AXR': {'tag': ['x'], },
	'@AP': {'tag': ['x'], },
	'@AZ': {'tag': ['x'], },
	'@DS': {'tag': ['x'], },
	'@DC': {'tag': ['x'], },
	'@DI': {'tag': ['x'], },
	'@DZ': {'tag': ['x'], },
	'@ADZ': {},
	'@NKC': {},
	'@NK': {},
	'@BOMB': {},
	'@BOMBP': {},
	'@BOMBD': {},
	'@HALF': {},
	'@KR1': {'actors': ['gk', 'xtd'], },
	'@KR': {},
	'@KD': {},
	'@CRT': {'actors': ['gc', 'xtd'], 'targets': ['gc', 'pT', 'xtd'], 'targetTeamIndex': ['td'], },
	'@CJJ': {'tag': ['td'], 'actors': ['gc', 'x'], 'targets': ['gc', 'x'], 'juniorIDList': ['t-2'], 'spyIDList': ['t2'], 'updateActors': ['t2'], 'updateDeadDelayed': ['t-2'], },
	'@CRS': {'tag': ['td'], 'actors': ['gc', 'x'], 'targets': ['gc', 'x', 'pT'], 'targetExtraLifeCount': ['m'], 'updateActors': ['tpT'], 'updateDeadDelayed': ['tpT'], },
	'@CTJ': {'actors': ['gc', 'x'], 'targets': ['gc', 'x', 't-4'], 'updateDeadDelayed': ['tpT'], },
	'@CXJ': {'tag': ['td'], 'targets': ['gc', 'x'], },
	'@CR': {'actors': ['gc', 'xtd'], 'updateDeadDelayed': ['tA'], },
	'@WR': {'actors': ['t-1'], 'updateActors': ['t-1'], },
	'@JSR1': {'actors': ['t-1'], 'targets': ['gc'], 'juniorIDList': ['t-2'], 'spyIDList': ['t2'], },
	'@JSR2': {'tag': ['gc'], },
	'@WLR': {'actors': ['t-1'], 'targets': ['t-4'], 'updateActors': ['t-4'], },
	'@JR': {'actors': ['t-2'], 'updateActors': ['t-2'], },
	'@TR': {'actors': ['t-4'], 'updateActors': ['t-4'], },
	'@SR': {'actors': ['t2'], 'updateActors': ['t2'], },
	'@KGR': {'actors': ['t3'], 'updateActors': ['t3'], },
	'@KGR2': {'tag': ['tA'], 'actors': ['t3'], },
	'@LR': {'actors': ['tpA'], 'targets': ['tpT'], 'updateActors': ['tpT'], 'updateTargets': ['tpA'], },
	'@TVR': {'actors': ['pA', 'xtd'], },
	'@WRD': {'actors': ['tpA'], },
	'@WR1': {'updateAll': ['tpA'], },
	'@WR1S': {},
	'@WR1T': {},
	'@WR2': {'updateAll': ['tpA'], },
	'@WR2E': {'tag': ['tpT'], 'targetExtraLifeCount': ['m'], },
	'@WR3': {'livesStolenList': ['m'], 'selfExtraLifeCount': ['m'], 'updateAll': ['tpA'], },
	'@WR4': {'updateAll': ['tpA'], },
	'@WR4R': {},
	'@WR5': {'updateAll': ['tpA'], },
	'@WR5R': {},
	'@WR6': {'updateAll': ['tpA'], },
	'@WR6E': {'resultCardList': ['gc', 'allT'], },
	'@WR7': {'updateAll': ['tpA'], },
	'@WR7R': {},
	'@LS': {'updateAll': ['tpA', 'tpT'], },
};

targetTemplateDict = {
	'lv#':			{'tag': 'lv#', 'p': [''],   'a': '#', 'channel': '50', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 2, 'legal': [], 'max': 1, },
	'kv#':			{'tag': 'kv#', 'p': ['gk'], 'a': '#', 'channel': '51', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 2, 'legal': [], 'max': 1, },
	'cv#':			{'tag': 'cv#', 'p': ['gc'], 'a': '#', 'channel': '52', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 2, 'legal': [], 'max': 2, },
	'civ#':			{'tag': 'civ#', 'p': ['gc'], 'a': '#', 'channel': '52', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 2, 'legal': [], 'max': 1, },
	'crv#':			{'tag': 'crv#', 'p': ['gc'], 'a': '#', 'channel': '52', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 2, 'legal': [], 'max': 3, },
	'av#':			{'tag': 'av#', 'p': ['xa'], 'a': '#', 'channel': '70', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 2, 'legal': [], 'max': 3, },
	'adv#':			{'tag': 'adv#', 'p': ['xa'], 'a': '#', 'channel': '70', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 6, 'legal': [], 'max': 1, },
	'dv#':			{'tag': 'dv#', 'p': ['xd'], 'a': '#', 'channel': '71', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 2, 'legal': [], 'max': 2, },
	'lvm':			{'tag': 'lvm', 'p': [''],   'a': 'm', 'channel': '50', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 2, 'legal': [], 'max': 1, },
	'kvm':			{'tag': 'kvm', 'p': ['gk'], 'a': 'm', 'channel': '51', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 2, 'legal': [], 'max': 1, },
	'cvm':			{'tag': 'cvm', 'p': ['gc'], 'a': 'm', 'channel': '52', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 2, 'legal': [], 'max': 2, },
	'civm':			{'tag': 'civm', 'p': ['gc'], 'a': 'm', 'channel': '52', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 2, 'legal': [], 'max': 1, },
	'crvm':			{'tag': 'crvm', 'p': ['gc'], 'a': 'm', 'channel': '52', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 2, 'legal': [], 'max': 3, },
	'avm':			{'tag': 'avm', 'p': ['xa'], 'a': 'm', 'channel': '70', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 2, 'legal': [], 'max': 3, },
	'advm':			{'tag': 'advm', 'p': ['xa'], 'a': 'm', 'channel': '70', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 6, 'legal': [], 'max': 1, },
	'dvm':			{'tag': 'dvm', 'p': ['xd'], 'a': 'm', 'channel': '71', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 2, 'legal': [], 'max': 2, },
	'char0':		{'tag': 'char0', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 1, 'legal': [], 'max': 1, },
	'char1':		{'tag': 'char1', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 1, 'legal': [], 'max': 1, },
	'char2':		{'tag': 'char2', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 1, 'legal': [], 'max': 1, 'blacklist': '#', },
	'char3':		{'tag': 'char3', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 1, 'legal': [], 'max': 1, },
	'char4':		{'tag': 'char4', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 0, 'legal': [], 'max': 0, },
	'char5':		{'tag': 'char5', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 7, 'legal': [], 'max': 1, },
	'char6':		{'tag': 'char6', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 0, 'legal': [], 'max': 0, },
	'char7':		{'tag': 'char7', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 0, 'legal': [], 'max': 0, },
	'char8':		{'tag': 'char8', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 4, 'legal': [], 'max': 1, },
	'char8-J':		{'tag': 'char8-J', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 1, 'legal': [], 'max': 1, },
	'char8-GD':		{'tag': 'char8-GD', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 0, 'legal': [], 'max': 0, },
	'char9':		{'tag': 'char9', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 0, 'legal': [], 'max': 0, },
	'char10':		{'tag': 'char10', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 0, 'legal': [], 'max': 0, },
	'char11':		{'tag': 'char11', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 0, 'legal': [], 'max': 0, },
	'char12':		{'tag': 'char12', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 0, 'legal': [], 'max': 0, },
	'char13':		{'tag': 'char13', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': true, 'style': 1, 'legal': [], 'max': 1, },
	'char14':		{'tag': 'char14', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 1, 'legal': [], 'max': 1, },
	'char14-2':		{'tag': 'char14-2', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 6, 'legal': [], 'max': 1, },
	'char15':		{'tag': 'char15', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 1, 'legal': [], 'max': 1, },
	'char15-2':		{'tag': 'char15-2', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': true, 'style': 4, 'legal': [], 'max': 1, },
	'char16':		{'tag': 'char16', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 0, 'legal': [], 'max': 0, },
	'char17':		{'tag': 'char17', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 1, 'legal': [], 'max': 1, 'blacklist': '#', },
	'char18':		{'tag': 'char18', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': true, 'style': 4, 'legal': [], 'max': 1, },
	'char19':		{'tag': 'char19', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 0, 'legal': [], 'max': 0, },
	'char20':		{'tag': 'char20', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 1, 'legal': [], 'max': 1, },
	'char21':		{'tag': 'char21', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': true, 'style': 3, 'legal': [], 'max': 1, },
	'char22':		{'tag': 'char22', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 0, 'legal': [], 'max': 0, },
	'char23':		{'tag': 'char23', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 1, 'legal': [], 'max': 1, 'blacklist': '#', },
	'char24':		{'tag': 'char24', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 1, 'legal': [], 'max': 1, },
	'char25':		{'tag': 'char25', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 0, 'legal': [], 'max': 0, },
	'char26':		{'tag': 'char26', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 1, 'legal': [], 'max': 1, },
	'char27':		{'tag': 'char27', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 1, 'legal': [], 'max': 1, },
	'char28':		{'tag': 'char28', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 1, 'legal': [], 'max': 1, },
	'char29':		{'tag': 'char29', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 0, 'legal': [], 'max': 0, },
	'char30':		{'tag': 'char30', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 1, 'legal': [], 'max': 1, },
	'char31':		{'tag': 'char31', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 1, 'legal': [], 'max': 1, },
	'char31-2':		{'tag': 'char31-2', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 6, 'legal': [], 'max': 1, },
	'char32':		{'tag': 'char32', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 8, 'legal': [], 'max': 3, },
	'char33':		{'tag': 'char33', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 1, 'legal': [], 'max': 1, },
	'char34':		{'tag': 'char34', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 1, 'legal': [], 'max': 1, },
	'char35':		{'tag': 'char35', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 1, 'legal': [], 'max': 1, },
	'char36':		{'tag': 'char36', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 6, 'legal': [], 'max': 1, },
	'char37':		{'tag': 'char37', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 0, 'legal': [], 'max': 0, },
	'char38':		{'tag': 'char38', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 1, 'legal': [], 'max': 1, },
	'char39':		{'tag': 'char39', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 5, 'legal': [], 'max': 1, },
	'char40':		{'tag': 'char40', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 1, 'legal': [], 'max': 3, },
	'char41':		{'tag': 'char41', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 1, 'legal': [], 'max': 1, },
	'char42':		{'tag': 'char42', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 1, 'legal': [], 'max': 2, },
	'char43':		{'tag': 'char43', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 1, 'legal': [], 'max': 2, },
	'char44':		{'tag': 'char44', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 1, 'legal': [], 'max': 2, },
	'char45':		{'tag': 'char45', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 6, 'legal': [], 'max': 3, },
	'char46':		{'tag': 'char46', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': true, 'style': 0, 'legal': [], 'max': 0, },
	'char47':		{'tag': 'char47', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 5, 'legal': [], 'max': 1, },
	'char48':		{'tag': 'char48', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': true, 'style': 0, 'legal': [], 'max': 0, },
	'char49':		{'tag': 'char49', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 0, 'legal': [], 'max': 0, },
	'char50':		{'tag': 'char50', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': true, 'style': 1, 'legal': [], 'max': 1, },
	'char51':		{'tag': 'char51', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': true, 'style': 1, 'legal': [], 'max': 1, },
	'char51-2':		{'tag': 'char51-2', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 6, 'legal': [], 'max': 1, },
	'char52':		{'tag': 'char52', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': true, 'style': 1, 'legal': [], 'max': 1, },
	'char53':		{'tag': 'char53', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': true, 'style': 0, 'legal': [], 'max': 0, },
	'char54':		{'tag': 'char54', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': true, 'style': 8, 'legal': [], 'max': 2, },
	'char55':		{'tag': 'char55', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': true, 'style': 1, 'legal': [], 'max': 1, },
	'char56':		{'tag': 'char56', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 4, 'legal': [], 'max': 1, },
/*	'char15':		{'tag': 'char15', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 1, 'legal': [], 'max': 1, }, //copycat
	'char15-2':		{'tag': 'char15-2', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': true, 'style': 4, 'legal': [], 'max': 1, },
	'char18':		{'tag': 'char18', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': true, 'style': 4, 'legal': [], 'max': 1, },
	'char21':		{'tag': 'char21', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': true, 'style': 3, 'legal': [], 'max': 1, },
	'char48':		{'tag': 'char48', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': true, 'style': 0, 'legal': [], 'max': 0, },
	'char50':		{'tag': 'char50', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': true, 'style': 1, 'legal': [], 'max': 1, },
	'char51':		{'tag': 'char51', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': true, 'style': 1, 'legal': [], 'max': 1, },
	'char51-2':		{'tag': 'char51-2', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 6, 'legal': [], 'max': 1, },
	'char52':		{'tag': 'char52', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': true, 'style': 1, 'legal': [], 'max': 1, },
	'char53':		{'tag': 'char53', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': true, 'style': 0, 'legal': [], 'max': 0, },
	'char54':		{'tag': 'char54', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': true, 'style': 8, 'legal': [], 'max': 2, },
	'char55':		{'tag': 'char55', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': true, 'style': 1, 'legal': [], 'max': 1, },*/
	'char57':		{'tag': 'char57', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 1, 'legal': [], 'max': 1, },
	'char58':		{'tag': 'char58', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 1, 'active': null, 'style': 0, 'legal': [], 'max': 0, },
	'wd1':			{'tag': 'wd1', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 9, 'legal': [], 'max': 1, },
	'wd2':			{'tag': 'wd2', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 9, 'legal': [], 'max': 2, },
	'wd3':			{'tag': 'wd3', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': null, 'style': 9, 'legal': [], 'max': 3, },
	'wr1':			{'tag': 'wr1', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': true, 'style': 8, 'legal': [], 'max': 2, 'blacklist': '#', },
	'wr2':			{'tag': 'wr2', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': true, 'style': 8, 'legal': [], 'max': 2, 'blacklist': '#', },
	'wr3':			{'tag': 'wr3', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': true, 'style': 8, 'legal': [], 'max': 3, },
	'wr4':			{'tag': 'wr4', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': true, 'style': 8, 'legal': [], 'max': 1, 'blacklist': '#', },
	'wr5':			{'tag': 'wr5', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': true, 'style': 8, 'legal': [], 'max': 1, },
	'wr6':			{'tag': 'wr6', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': true, 'style': 8, 'legal': [], 'max': 3, },
	'wr7':			{'tag': 'wr7', 'p': ['p#'], 'a': '#', 'channel': '#', 't': [], 'useCount': 0, 'locked': 0, 'active': true, 'style': 8, 'legal': [], 'max': 2, },
};